name:                scoper
version:             0.1.0.0
github:              "iarekk/scoper"
license:             MIT
author:              "Iarek Kovtunenko"
maintainer:          "iarek.kovtunenko@gmail.com"
copyright:           "2020 Iarek Kovtunenko"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/scoper#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- bytestring

library:
  source-dirs: src

executables:
  scoper-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Werror
    - -fwarn-incomplete-patterns
    dependencies:
    - scoper

tests:
  scoper-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - scoper
