name: Haskell CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        #-- ghc-version: '8.8.2'
        #--cabal-version: '3.0'
        enable-stack: true
        stack-version: 'latest'
    - name: Build
      run: stack build
